# Generated by Django 3.0.5 on 2024-11-23 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('folio', models.CharField(default='Sin Folio', max_length=255)),
                ('editorial', models.CharField(blank=True, max_length=255, null=True)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_control', models.CharField(max_length=20, unique=True)),
                ('nombre1', models.CharField(max_length=100)),
                ('grado_y_grupo', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('generacion', models.CharField(max_length=50)),
                ('titulo_de_tesis', models.CharField(max_length=200)),
                ('asesor_academico', models.CharField(max_length=100)),
                ('asesor_empresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_de_barras', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(default='No especificado', max_length=50)),
                ('nombre', models.CharField(default='Nombre no especificado', max_length=255)),
                ('grado', models.CharField(default='No especificado', max_length=255)),
                ('grupo', models.CharField(default='No especificado', max_length=50)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('devuelto', 'Devuelto')], max_length=50)),
                ('codigo_barras', models.CharField(max_length=255)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Libro')),
            ],
        ),
    ]
