# Generated by Django 3.0.5 on 2024-11-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesis',
            old_name='nombre1',
            new_name='nombre',
        ),
    ]
