# Generated by Django 5.1.3 on 2024-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUser',
            new_name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
